### ISSUE TITLE
Location is resetting to London after restart

### ISSUE THREAD

**Issue by Gudguy7** [Rahul-Blatz/Complete-World-Clock-Flutter#1]
Location is resetting to London after restart.

**Comment by Rahul-Blatz** [comment]
yeah.. it doesn't have any state management.. I developed this to get my way around with flutter and learning from it.. Sorry to disappoint you.. But, I'll try to implement it

**Comment by Rahul-Blatz** [comment]
> 
> 
> Location is resetting to London after restart.

Solved the issue by using shared preferences.
